version: "3.6"

services:

  database:
    volumes:
      - ../../db_dump:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT:-5432}:5432
    depends_on:
      - rabbitmq

  project:
    build: ../project
    volumes:
      - ../project:/app
    depends_on:
      - web-service

  adminer:
    ports:
      - ${ADMINER_PORT:-63}:8080

  web-service:
    depends_on:
      - database
    ports:
      - ${WEB_SERVICE_PORT:-9898}:8080

  rabbitmq:
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGER_PORT:-15672}:15672